import type { LangKey } from "./translations";

type LocalizedText = Record<LangKey, string>;

export type ServiceItem = { id: string; slug: string; title: LocalizedText; excerpt: LocalizedText; image: string; category: LocalizedText };
export type PortfolioItem = { id: string; slug: string; client: LocalizedText; service: LocalizedText; image: string; category: string };
export type Contact = { phone: string; phoneHref: string; email: string; address: string; hours: string; instagram: string; telegram: string; youtube: string };

export const contact: Contact = {
  phone: "+998 77 300 45 00",
  phoneHref: "tel:+998773004500",
  email: "info@togogrouppro.uz",
  address: "Toshkent, Mirzo Ulug'bek tumani, Gulzor, 2-Bunyodkorlik tor ko'chasi, 9-uy",
  hours: "Dushanba — Juma, 09:00 — 19:00 | Shanba, 09:00 — 18:30",
  instagram: "https://www.instagram.com/reklama_togo_group/",
  telegram: "https://t.me/togo_group_pro",
  youtube: "https://www.youtube.com/@togogrouppro",
};

export const services: ServiceItem[] = [
  {
    id: "led",
    slug: "led-harflar",
    title: { uz: "LED Harflar", ru: "Объемные буквы", en: "LED Letters" },
    excerpt: {
      uz: "Har qanday turdagi yoritiladigan harflar",
      ru: "Светящиеся буквы любого типа",
      en: "Illuminated letters of any type",
    },
    image: "/img/services/led-harflar.webp",
    category: { uz: "LED", ru: "LED", en: "LED" },
  },
  {
    id: "lightbox",
    slug: "lightbox",
    title: { uz: "Lightbox", ru: "Лайтбокс", en: "Lightbox" },
    excerpt: {
      uz: "Yoritiladigan qutilar va panellar",
      ru: "Световые короба и панели",
      en: "Illuminated boxes and panels",
    },
    image: "/img/services/lightbox.webp",
    category: { uz: "Lightbox", ru: "Лайтбокс", en: "Lightbox" },
  },
  {
    id: "banner",
    slug: "banner",
    title: { uz: "Banner", ru: "Баннер", en: "Banner" },
    excerpt: {
      uz: "Tashqi va ichki banner ishlab chiqarish",
      ru: "Изготовление наружных и внутренних баннеров",
      en: "Indoor and outdoor banner production",
    },
    image: "/img/services/banner.webp",
    category: { uz: "Banner", ru: "Баннер", en: "Banner" },
  },
  {
    id: "rollup",
    slug: "roll-up",
    title: { uz: "Roll Up", ru: "Ролл-ап", en: "Roll Up" },
    excerpt: {
      uz: "Rolap stendlar va konstruksiyalar",
      ru: "Ролл-ап стенды и конструкции",
      en: "Roll-up stands and structures",
    },
    image: "/img/services/roll-up.webp",
    category: { uz: "Stend", ru: "Стенд", en: "Stand" },
  },
  {
    id: "stend",
    slug: "stend",
    title: { uz: "Stend", ru: "Стенд", en: "Stand" },
    excerpt: {
      uz: "Ko'rgazma va savdo stendlar",
      ru: "Выставочные и торговые стенды",
      en: "Exhibition and retail stands",
    },
    image: "/img/services/stend.webp",
    category: { uz: "Stend", ru: "Стенд", en: "Stand" },
  },
  {
    id: "auto",
    slug: "avto-reklama",
    title: { uz: "Avto reklama", ru: "Реклама на авто", en: "Car Branding" },
    excerpt: {
      uz: "Avtomobillarga brend va reklama yopishtirish",
      ru: "Брендирование и оклейка автомобилей рекламой",
      en: "Vehicle branding and advertising wraps",
    },
    image: "/img/services/avto-reklama.webp",
    category: { uz: "Avto", ru: "Авто", en: "Auto" },
  },
  {
    id: "award",
    slug: "statuetka",
    title: { uz: "Statuetka", ru: "Статуэтка", en: "Awards" },
    excerpt: {
      uz: "Akril, metal va boshqa esdalik sovg'alar",
      ru: "Акриловые, металлические и другие памятные сувениры",
      en: "Acrylic, metal and other keepsake awards",
    },
    image: "/img/services/statuetka.webp",
    category: { uz: "Sovg'a", ru: "Сувенир", en: "Gift" },
  },
  {
    id: "uv",
    slug: "uv-print",
    title: { uz: "UV Print", ru: "УФ печать", en: "UV Print" },
    excerpt: {
      uz: "Turli materiallarga UV bosma xizmati",
      ru: "УФ печать на различных материалах",
      en: "UV printing on a variety of materials",
    },
    image: "/img/services/uv-print.webp",
    category: { uz: "Print", ru: "Печать", en: "Print" },
  },
];

export const portfolio: PortfolioItem[] = [
  {
    id: "p1",
    slug: "p1",
    client: { uz: "Hajmli Harflar va LED Fasad", ru: "Объемные буквы и LED фасад", en: "Volumetric Letters & LED Facade" },
    service: { uz: "Tashqi reklama", ru: "Наружная реклама", en: "Outdoor Advertising" },
    category: "Tashqi reklama",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2024-08-20_10-26-48%20(2).jpg",
  },
  {
    id: "p2",
    slug: "p2",
    client: { uz: "Artel Showroom & Brending", ru: "Artel Шоурум и брендинг", en: "Artel Showroom & Branding" },
    service: { uz: "LED Harf", ru: "Объемные буквы", en: "LED Letters" },
    category: "LED Harf",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2024-04-21_23-12-13.jpg",
  },
  {
    id: "p3",
    slug: "p3",
    client: { uz: "Litto Hotel Yoritgichlari", ru: "Освещение Litto Hotel", en: "Litto Hotel Signage" },
    service: { uz: "LED Logo", ru: "LED Логотип", en: "LED Logo" },
    category: "LED Logo",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2024-08-20_10-26-48.jpg",
  },
  {
    id: "p4",
    slug: "p4",
    client: { uz: "Lightme Office Lightbox", ru: "Lightme Офис Лайтбокс", en: "Lightme Office Lightbox" },
    service: { uz: "Lightbox", ru: "Лайтбокс", en: "Lightbox" },
    category: "Lightbox",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2024-04-21_23-12-16.jpg",
  },
  {
    id: "p5",
    slug: "p5",
    client: { uz: "Mövenpick Fasad Reklamasi", ru: "Фасадная реклама Mövenpick", en: "Mövenpick Facade Advertising" },
    service: { uz: "Tashqi reklama", ru: "Наружная реклама", en: "Outdoor Advertising" },
    category: "Tashqi reklama",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2024-03-21_15-14-53.jpg",
  },
  {
    id: "p6",
    slug: "p6",
    client: { uz: "Ideal Furniture Stendi", ru: "Стенд Ideal Furniture", en: "Ideal Furniture Stand" },
    service: { uz: "Stend", ru: "Стенд", en: "Stand" },
    category: "Stend",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2024-06-08_23-17-29.jpg",
  },
  {
    id: "p7",
    slug: "p7",
    client: { uz: "Nest One Fasad Brending", ru: "Фасадный брендинг Nest One", en: "Nest One Facade Branding" },
    service: { uz: "Tashqi reklama", ru: "Наружная реклама", en: "Outdoor Advertising" },
    category: "Tashqi reklama",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2023-07-10_21-04-45.jpg",
  },
  {
    id: "p8",
    slug: "p8",
    client: { uz: "UzAuto Motors Stendi", ru: "Стенд UzAuto Motors", en: "UzAuto Motors Stand" },
    service: { uz: "Stend", ru: "Стенд", en: "Stand" },
    category: "Stend",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2023-07-02_11-45-24.jpg",
  },
  {
    id: "p9",
    slug: "p9",
    client: { uz: "Korzinka Avto Reklama", ru: "Реклама на авто Korzinka", en: "Korzinka Car Branding" },
    service: { uz: "Avto reklama", ru: "Реклама на авто", en: "Car Branding" },
    category: "Avto reklama",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2023-07-10_21-04-47.jpg",
  },
  {
    id: "p10",
    slug: "p10",
    client: { uz: "N-Clinic Reklama", ru: "Реклама N-Clinic", en: "N-Clinic Advertising" },
    service: { uz: "Tashqi reklama", ru: "Наружная реклама", en: "Outdoor Advertising" },
    category: "Tashqi reklama",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2024-06-10_11-06-45.jpg",
  },
  {
    id: "p11",
    slug: "p11",
    client: { uz: "Tashqi Banner va Stendlar", ru: "Наружные баннеры и стенды", en: "Outdoor Banners & Stands" },
    service: { uz: "Stend", ru: "Стенд", en: "Stand" },
    category: "Stend",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2023-08-06_16-13-38.jpg",
  },
  {
    id: "p12",
    slug: "p12",
    client: { uz: "Savdo Markazi Brending", ru: "Брендинг торгового центра", en: "Shopping Mall Branding" },
    service: { uz: "Lightbox", ru: "Лайтбокс", en: "Lightbox" },
    category: "Lightbox",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2024-08-26_10-36-57.jpg",
  },
  {
    id: "p13",
    slug: "p13",
    client: { uz: "Akril va LED Harflar", ru: "Акриловые и LED буквы", en: "Acrylic & LED Letters" },
    service: { uz: "LED Harf", ru: "Объемные буквы", en: "LED Letters" },
    category: "LED Harf",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2023-10-04_22-34-29.jpg",
  },
  {
    id: "p14",
    slug: "p14",
    client: { uz: "Sanoat Korxonasi Fasad", ru: "Фасад промышленного предприятия", en: "Industrial Facility Facade" },
    service: { uz: "Tashqi reklama", ru: "Наружная реклама", en: "Outdoor Advertising" },
    category: "Tashqi reklama",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2023-10-04_22-34-33.jpg",
  },
  {
    id: "p15",
    slug: "p15",
    client: { uz: "Kran va Baland Bino Reklamasi", ru: "Реклама на кране и высотном здании", en: "Crane & High-Rise Advertising" },
    service: { uz: "Tashqi reklama", ru: "Наружная реклама", en: "Outdoor Advertising" },
    category: "Tashqi reklama",
    image: "https://togogrouppro.uz/storage/portfolio-images/photo_2023-10-04_22-34-31.jpg",
  },
];
